[workspace]

members = [
    "cjdns-core",
    "cjdns-keys",
    "cjdns-bencode",
    "cjdns-bytes",
    "cjdns-ann",
    "cjdns-hdr",
    "cjdns-ctrl",
    "cjdns-admin",
    "cjdns-sniff",
    "cjdns-snode",
    "netchecksum",
]
