[package]
name = "cjdns-entities"
version = "0.1.0"
authors = ["Eenae <alexey@mixbytes.io>"]
edition = "2018"
license = "GPL-3.0"
description = "Inter-crate cjdns types, structs & traits"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
