[package]
name = "cjdns-admin"
version = "0.1.0"
authors = [
    "Alex Kordys <a.kordys@mixbytes.io>"
]
edition = "2018"
license = "GPL-3.0"
description = "cjdns node admin lib & binary"

[dependencies]
#TODO This is a patched fork of `https://github.com/P3KI/bendy/`, need to move it under cjdns project umbrella.
bendy = { git = "https://github.com/a-kordys/bendy-cjdns", tag = "v0.3.2-cjdns", features = ["std", "serde"] }
#bendy = { version = "0.3", features = ["std", "serde"] } # bencode support
dirs = "3.0"
hex = "0.4"
rand = "0.7"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sodiumoxide = "0.2"