[package]
name = "netchecksum"
version = "0.1.0"
authors = [
    "Alex Kordys <a.kordys@mixbytes.io>"
]
edition = "2018"
license = "GPL-3.0"
description = "The 1s complement checksum used by TCP, UDP and ICMP"

[dependencies]

[dev-dependencies.hex]
version = "0.4"